apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    app: labels
    purpose: demonstrate-labels
    tire: test
    env:
    -  name: ENVIRONMENT
       value: "dev"
    -  name: VERSION
       value: "1.0"
