apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    app: labels
    purpose: demonstrate-labels
    tire: test
    environment: dev
  annotations:
    description: "This pod is used to demonstrate the use of labels and annotations in Kubernetes."
    owner: "DevOps Team"
    version: "1.0"
    build-date: "2024-06-15"
spec:
  containers:
    - name: labels-container
      image: nginx:latest

    - name: labels-container2
      image: alpine:latest