apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-01871ca0e67fa4752


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-1
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-1a
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi