apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-svc
  namespace: roboshop
  labels:
    app: mongodb
    purpose: statefulset
    project: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
    purpose: statefulset
    project: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      purpose: statefulset
      project: mongodb
  serviceName: "mongodb-headless-svc"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
        purpose: statefulset
        project: mongodb
    spec:
      containers:
      - name: mongodb
        image: mohan9866007322/mongodb:v1
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi
